---
mysetting:
  notices: &1
    label: 通知公告
    title: 标题
    notice_date: 日期
    content: 内容
  reports: &2
    title: 标题
    content: 正文
  models: &3
    label: ''
    name: 名称
    image: 图像
    index: 列表
    new: 新建
    edit: 编辑
    show: 详情
    form: 表单
    js: js
    scss: scss
    admin: 添加到后台
  properties: &4
    label: 嵌套显示的属性
    name: 属性名
    tag: 标签
  relates: &5
    label: ''
    type: 关联类型
    obj: 对象
  templates: &6
    label: 模板
    name: 英文名称
    cn_name: 中文名称
    nest: 需要在页面嵌套的一对多属性
    image: 多个图片
    attachment: 多个附件
    one_image: 一个图片
    one_attachment: 一个附件
    index: 列表
    new: 新建
    edit: 编辑
    show: 详情
    form: 表单
    js: js
    scss: scss
    download: 下载表格
    upload: 上传解析表格
    admin: 添加到后台
    current_user: current_user
  natures: &7
    label: ''
    name: 英文属性名
    type: 类型
    title: 中文属性名
    tag: 标签
  spiders: &8
    label: 爬虫
    link: 请求地址
    cookie: cookie
    agent: agent
    content_type: content_type
    page: 页码
    file: 文件名带后缀
    referer: referer
    host: host
    redirection: redirection
  selectors: &9
    label: 选择器
    name: 选择器名称
    category: 类型
    title: 标题
    categories:
      text:
        info: 文本
        value: '0'
      attr:
        info: 属性
        value: '1'
      img:
        info: 图片
        value: '2'
defaults:
  admins: &10
    class_name: all
    email: myzn@world.com
    phone: '17305379588'
    password: dagening@521
  users: &11
    class_name: User
    opening: 0
    pending: 1
    rejected: 2
    passed: 3
    opening_title: 新用户
    pending_title: 待审核
    rejected_title: 不通过
    passed_title: 通过
    phone: 电话
    password: 密码
    password_confirmation: 确认密码
    name: 姓名
    identity: 身份证
    alipay: 支付宝
    status: 认证状态
    level: 等级
    inviter: 邀请者
  roles: &12
    label: 角色
    name: 名称
    class_name: Role
    super_admin: 超级管理员
    role_fct: 厂区用户
    role_grp: 集团用户
    role_qesbank: 题库管理
    role_law: 法律制度
    role_learn: 在线学习
    role_notice: 通知公告
    role_advise: 意见反馈
    role_ctg: 分类管理
    role_student: 学生管理
  permissions: &13
    super_admin: 管理系统所有资源
    label: 权限管理
    name: 名称
    subject_class: controller单数名称
    action: action
    description: 描述
  systems: &14
    poundage: 0.1
    commision: 0.1
    authc_pay: 1
    host: http://192.168.100.119
    status_en_yes: true
    status_en_no: false
    status_yes: 是
    status_no: 否
    status_public: '1'
    status_private: '0'
    default_str: ''
    default_num: 0
    default_boolean: true
    per_page: 20
    index: index
    new: new
    show: show
    delete: delete
    edit: edit
    btn_upload: 上传
    btn_back: 返回
    btn_next: 下一步
    btn_edit: 编辑
    btn_new: 添加
    btn_show: 详情
    btn_delete: 删除
    btn_save: 保存
    company_name: 山东公用控股平安公用后台管理系统
    opening: 新用户
    pending: 待审核
    rejected: 不通过
    passed: 通过
    txt: 文本
    pdf: PDF
  states: &15
    opening: opening
    selecting: selecting
    selected: selected
    completed: completed
    canceled: canceled
    uploading: uploading
    uploaded: uploaded
    ongoing: ongoing
    outbound: outbound
    awaiting: awaiting
    pending: pending
    passed: passed
    working: working
  trade_orders: &16
    number: 订单编号
    price: 价格
    state: 状态
    name: 姓名
    phone: 电话
    address: 地址
    wayno: 物流信息
    opening: opening
    opening_title: 新建
    pending: pending
    pending_title: 待支付
    paid: paid
    paid_title: 已支付,待发货
    departed: departed
    departed_title: 已发货
    completed: completed
    completed_title: 已完成
    canceled: canceled
    canceled_title: 已取消
  extract_cashes: &17
    coin: 提取金额
    status: 状态
    pending: pending
    pending_title: 待审核
    agree: agree
    agree_title: 同意
    disagree: disagree
    disagree_title: 不同意
  file_libs: &18
    label: 文件库
    name: 文件名
    path: 路径
    file_type: 文件类型
    doc: '0'
    xls: '1'
    pdf: '2'
    img: '3'
    ppt: '4'
    mp4: '5'
    txt: '6'
  archives: &19
    label: 档案库
    name: 名称
    desc: 备注
  portfolios: &20
    label: 文件夹
    name: 文件夹名
  examines: &21
    label: 考核资料自选库
    name: 名称
  exm_items: &22
    label: 一级目录
    name: 一级目录名
    hierarchy: 目录树
  agendas: &23
    label: 日程
    title: 标题
    content: 事务内容
    worktime: 时间
  statistics: &24
    label: 统计
    title: 标题
    xtitle: x轴标题
    ytitle: y轴标题
    legend: 图例
    data: 数据
  companies: &25
    label: 公司
    area: 地区
    name: 名称
    info: 简介
    lnt: 经度
    lat: 维度
  factories: &26
    label: 工厂
    area: 地区
    name: 名称
    info: 简介
    design: 设计处理水量
    lnt: 经度
    lat: 维度
    plan: 计划
  departments: &27
    label: 部门
    name: 名称
    info: 简介
  charts: &28
    line: '0'
    bar: '1'
    gauge: '2'
    table: '3'
    radar: '4'
    scatter_3d: '5'
    line_t: line
    bar_t: bar
    gauge_t: gauge
    table_t: table
    radar_t: radar
    scatter_3d_t: scatter_3d
  months: &29
    one: '1'
    one_t: 一月
    two: '2'
    two_t: 二月
    three: '3'
    three_t: 三月
    four: '4'
    four_t: 四月
    five: '5'
    five_t: 五月
    six: '6'
    six_t: 六月
    seven: '7'
    seven_t: 七月
    eight: '8'
    eight_t: 八月
    nine: '9'
    nine_t: 九月
    ten: '10'
    ten_t: 十月
    eleven: '11'
    eleven_t: 十一月
    twelve: '12'
    twelve_t: 十二月
  accounts: &30
    coin: 金额
    password: 安全密码
    number: 卡号
    award_sign_up: 10
    award_check_in: 5
    award_share: 30
    award_invite_sign_up: 10
    award_invite_recharge: 40
    enable: enable
    disable: disable
  wares: &31
    water_item: '0'
    sewage_item: '1'
    project_item: '2'
    repair_part: '3'
    emergency: '4'
    stuff: '5'
    device: '6'
    uphold: '7'
  productions: &32
    label: 生产设备
    name: 名称
  waters: &33
    label: 供水
    name: 名称
  water_ones: &34
    label: 供水一级分类
    name: 名称
  water_twos: &35
    label: 供水二级分类
    name: 名称
  water_items: &36
    label: 供水设备
    name: 名称
    idno: 编码
    unit: 单位
    mdno: 型号
    fct: 厂家
    desc: 备注
    count: 数量
  sewages: &37
    label: 污水
    name: 名称
  sewage_ones: &38
    label: 污水一级分类
    name: 名称
  sewage_twos: &39
    label: 污水二级分类
    name: 名称
  sewage_items: &40
    label: 污水设备
    name: 名称
    idno: 编码
    unit: 单位
    mdno: 型号
    fct: 厂家
    desc: 备注
    count: 数量
  projects: &41
    label: 工程
    name: 名称
  project_ones: &42
    label: 工程一级分类
    name: 名称
  project_twos: &43
    label: 工程二级分类
    name: 名称
  project_items: &44
    label: 工程知识
    name: 名称
    idno: 编码
    unit: 单位
    mdno: 型号
    fct: 厂家
    desc: 备注
    count: 数量
  repair_parts: &45
    label: 维修配件
    name: 名称
    idno: 编码
    unit: 单位
    mdno: 型号
    fct: 厂家
    desc: 备注
    count: 数量
  emergencies: &46
    label: 应急知识
    name: 名称
    idno: 编码
    unit: 单位
    mdno: 型号
    fct: 厂家
    desc: 备注
    count: 数量
  stuffs: &47
    label: 化学菌剂
    name: 名称
    idno: 编码
    unit: 单位
    mdno: 规格
    fct: 厂家
    desc: 备注
    count: 重量kg
  devices: &48
    label: 设备档案
    idno: 设备编号
    name: 设备名称
    mdno: 规格型号
    unit: 计量单位
    out_date: 出厂日期
    mount_date: 安装日期
    supplier: 供应商
    mfcture: 制造商
    pos: 安装位置
    pos_no: 安装位置编号
    life: 使用年限
    qrcode: 二维码
    state: 状态
    desc: 备注
    state_normal: 正常
    state_repair: 检修
    state_stop: 停用
  upholds: &49
    label: 维保记录
    uphold_date: 日期
    reason: 维保原因
    content: 维保内容
    cost: 费用
    state: 状态
  papers: &50
    label: 试卷
    name: 试卷名
    start_time: 考试开始时间
    end_time: 考试结束时间
    single: 单选题数量
    single_score: 单选题分值
    mcq: 多选题数量
    mcq_score: 多选题分值
    tof: 判断题数量
    tof_score: 判断题分值
    qaa: 问答题数量
    qaa_score: 问答题分值
    desc: 备注
    right: 对
    error: 错
  singles: &51
    label: 单选题
    title: 题目
  single_options: &52
    label: 单选选项
    title: 选项内容
    answer: 答案
  mcqs: &53
    label: 多选题
    title: 标题
  mcq_options: &54
    label: 多选题选项
    title: 标题
    answer: 答案
  tofs: &55
    label: 判断题
    title: 标题
    answer: 答案
  qaas: &56
    label: 问答题
    title: 标题
    answer: 答案
  qes_banks: &57
    label: 题库
    name: 题库名
    editor: 编辑
    single_count: 单选题数量
    mcq_count: 多选题数量
    tof_count: 判断题数量
    qaa_count: 问答题数量
    single_type: 单选题
    mcq_type: 多选题
    tof_type: 判断题
    qaa_type: 问答题
  error_logs: &58
    label: 错误日志
    name: 名称
    log_url: 路径
  students: &59
    label: 学生
    name: 姓名
    nickname: 微信昵称
    idno: 身份证号
    phone: 电话
  essays: &60
    label: 学习文章
    title: 标题
    dept: 部门
    article_date: 日期
    content: 文章内容
  advises: &61
    label: 意见反馈
    title: 标题
    content: 内容
  learn_ctgs: &62
    label: 在线答题分类
    name: 名称
    logo: logo
  law_ctgs: &63
    label: 法律制度类目
    name: 名称
  laws: &64
    label: 法律法规
    title: 标题
    pdt_date: 日期
    content: 内容
    dept: 部门
    ctg: 类别
development:
  notices: *1
  reports: *2
  models: *3
  properties: *4
  relates: *5
  templates: *6
  natures: *7
  spiders: *8
  selectors: *9
  admins: *10
  users: *11
  roles: *12
  permissions: *13
  systems: *14
  states: *15
  trade_orders: *16
  extract_cashes: *17
  file_libs: *18
  archives: *19
  portfolios: *20
  examines: *21
  exm_items: *22
  agendas: *23
  statistics: *24
  companies: *25
  factories: *26
  departments: *27
  charts: *28
  months: *29
  accounts: *30
  wares: *31
  productions: *32
  waters: *33
  water_ones: *34
  water_twos: *35
  water_items: *36
  sewages: *37
  sewage_ones: *38
  sewage_twos: *39
  sewage_items: *40
  projects: *41
  project_ones: *42
  project_twos: *43
  project_items: *44
  repair_parts: *45
  emergencies: *46
  stuffs: *47
  devices: *48
  upholds: *49
  papers: *50
  singles: *51
  single_options: *52
  mcqs: *53
  mcq_options: *54
  tofs: *55
  qaas: *56
  qes_banks: *57
  error_logs: *58
  students: *59
  essays: *60
  advises: *61
  learn_ctgs: *62
  law_ctgs: *63
  laws: *64
  carousels:
    label: 走马灯
    title: 标题
test:
  notices: *1
  reports: *2
  models: *3
  properties: *4
  relates: *5
  templates: *6
  natures: *7
  spiders: *8
  selectors: *9
  admins: *10
  users: *11
  roles: *12
  permissions: *13
  systems: *14
  states: *15
  trade_orders: *16
  extract_cashes: *17
  file_libs: *18
  archives: *19
  portfolios: *20
  examines: *21
  exm_items: *22
  agendas: *23
  statistics: *24
  companies: *25
  factories: *26
  departments: *27
  charts: *28
  months: *29
  accounts: *30
  wares: *31
  productions: *32
  waters: *33
  water_ones: *34
  water_twos: *35
  water_items: *36
  sewages: *37
  sewage_ones: *38
  sewage_twos: *39
  sewage_items: *40
  projects: *41
  project_ones: *42
  project_twos: *43
  project_items: *44
  repair_parts: *45
  emergencies: *46
  stuffs: *47
  devices: *48
  upholds: *49
  papers: *50
  singles: *51
  single_options: *52
  mcqs: *53
  mcq_options: *54
  tofs: *55
  qaas: *56
  qes_banks: *57
  error_logs: *58
  students: *59
  essays: *60
  advises: *61
  learn_ctgs: *62
  law_ctgs: *63
  laws: *64
production:
  notices: *1
  reports: *2
  models: *3
  properties: *4
  relates: *5
  templates: *6
  natures: *7
  spiders: *8
  selectors: *9
  admins: *10
  users: *11
  roles: *12
  permissions: *13
  systems: *14
  states: *15
  trade_orders: *16
  extract_cashes: *17
  file_libs: *18
  archives: *19
  portfolios: *20
  examines: *21
  exm_items: *22
  agendas: *23
  statistics: *24
  companies: *25
  factories: *26
  departments: *27
  charts: *28
  months: *29
  accounts: *30
  wares: *31
  productions: *32
  waters: *33
  water_ones: *34
  water_twos: *35
  water_items: *36
  sewages: *37
  sewage_ones: *38
  sewage_twos: *39
  sewage_items: *40
  projects: *41
  project_ones: *42
  project_twos: *43
  project_items: *44
  repair_parts: *45
  emergencies: *46
  stuffs: *47
  devices: *48
  upholds: *49
  papers: *50
  singles: *51
  single_options: *52
  mcqs: *53
  mcq_options: *54
  tofs: *55
  qaas: *56
  qes_banks: *57
  error_logs: *58
  students: *59
  essays: *60
  advises: *61
  learn_ctgs: *62
  law_ctgs: *63
  laws: *64
